=begin
PostPuma - OpenAPI 3.0

PostPuma API specifications

The version of the OpenAPI document: 1.0.0
Contact: support@postpuma.com
Generated by: https://github.com/openapitools/openapi-generator.git

=end
Rails.application.routes.draw do

  def add_openapi_route http_method, path, opts = {}
    full_path = path.gsub(/{(.*?)}/, ':\1')
    match full_path, to: "#{opts.fetch(:controller_name)}##{opts[:action_name]}", via: http_method
  end

  add_openapi_route 'GET', '/app/5afgg2-1egj4n-7612ng-g313ie/accounts/{accountUuid}', controller_name: 'accounts', action_name: 'show'
  add_openapi_route 'GET', '/app/5afgg2-1egj4n-7612ng-g313ie/accounts', controller_name: 'accounts', action_name: 'index'
  add_openapi_route 'DELETE', '/app/5afgg2-1egj4n-7612ng-g313ie/media', controller_name: 'media', action_name: 'delete_media_files'
  add_openapi_route 'GET', '/app/5afgg2-1egj4n-7612ng-g313ie/media/{mediaUuid}', controller_name: 'media', action_name: 'show'
  add_openapi_route 'GET', '/app/5afgg2-1egj4n-7612ng-g313ie/media', controller_name: 'media', action_name: 'index'
  add_openapi_route 'POST', '/app/5afgg2-1egj4n-7612ng-g313ie/media', controller_name: 'media', action_name: 'create'
  add_openapi_route 'POST', '/app/5afgg2-1egj4n-7612ng-g313ie/posts', controller_name: 'posts', action_name: 'create'
  add_openapi_route 'DELETE', '/app/5afgg2-1egj4n-7612ng-g313ie/posts/{postUuid}', controller_name: 'posts', action_name: 'destroy'
  add_openapi_route 'DELETE', '/app/5afgg2-1egj4n-7612ng-g313ie/posts', controller_name: 'posts', action_name: 'delete_posts'
  add_openapi_route 'GET', '/app/5afgg2-1egj4n-7612ng-g313ie/posts/{postUuid}', controller_name: 'posts', action_name: 'show'
  add_openapi_route 'GET', '/app/5afgg2-1egj4n-7612ng-g313ie/posts', controller_name: 'posts', action_name: 'index'
  add_openapi_route 'POST', '/app/5afgg2-1egj4n-7612ng-g313ie/posts/add-to-queue/{postUuid}', controller_name: 'posts', action_name: 'queue_post'
  add_openapi_route 'POST', '/app/5afgg2-1egj4n-7612ng-g313ie/posts/schedule/{postUuid}', controller_name: 'posts', action_name: 'schedule_post'
  add_openapi_route 'PUT', '/app/5afgg2-1egj4n-7612ng-g313ie/posts/{postUuid}', controller_name: 'posts', action_name: 'update'
  add_openapi_route 'POST', '/app/5afgg2-1egj4n-7612ng-g313ie/tags', controller_name: 'tags', action_name: 'create'
  add_openapi_route 'DELETE', '/app/5afgg2-1egj4n-7612ng-g313ie/tags/{tagUuid}', controller_name: 'tags', action_name: 'destroy'
  add_openapi_route 'GET', '/app/5afgg2-1egj4n-7612ng-g313ie/tags/{tagUuid}', controller_name: 'tags', action_name: 'show'
  add_openapi_route 'GET', '/app/5afgg2-1egj4n-7612ng-g313ie/tags', controller_name: 'tags', action_name: 'index'
  add_openapi_route 'PUT', '/app/5afgg2-1egj4n-7612ng-g313ie/tags/{tagUuid}', controller_name: 'tags', action_name: 'update'
end
