=begin
PostPuma - OpenAPI 3.0

PostPuma API specifications

The version of the OpenAPI document: 1.0.0
Contact: support@postpuma.com
Generated by: https://github.com/openapitools/openapi-generator.git

=end
class TagsController < ApplicationController

  def create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def destroy
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def show
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def index
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def update
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
