=begin
PostPuma - OpenAPI 3.0

PostPuma API specifications

The version of the OpenAPI document: 1.0.0
Contact: support@postpuma.com
Generated by: https://github.com/openapitools/openapi-generator.git

=end


class Version < ApplicationRecord
  validates_presence_of :account_id
  validates_presence_of :is_original
  validates_presence_of :content

end
